Refaktorering (1)/app.py
# Importing the necessary modules and libraries
from flask import Flask, g as appContext
import sqlite3
from routes.authenticationBlueprint import autheticationBlueprint
from flask_talisman import Talisman
from routes.imageBlueprint import imageBlueprint
from routes.commentBlueprint import commentBlueprint
from routes.profileBlueprint import userBlueprint
from routes.indexBlueprint import indexBlueprint


app = Flask(__name__) 
talisman = Talisman(app)
app.config.from_object('config')
app.jinja_env.autoescape = True    

@app.before_request
def before_request():
    app.db = connect_db()


@app.teardown_request
def teardown_request(exception):
    db = getattr(appContext, 'db', None)
    if db is not None:
        db.close()


def connect_db():
    return sqlite3.connect(app.config['DATABASE'])


# Registering the blueprint
app.register_blueprint(indexBlueprint, url_prefix='/')
app.register_blueprint(autheticationBlueprint, url_prefix='/authentication')
app.register_blueprint(imageBlueprint, url_prefix='/image' )
app.register_blueprint(commentBlueprint, url_prefix='/comment')
app.register_blueprint(userBlueprint, url_prefix='/profile')

if __name__ == '__main__': #__name__ variable value is __main__  in the root script
    app.run(host='0.0.0.0', port=3333, ssl_context='adhoc')

Refaktorering (1)/controllers/EntryController.py
from sys import abiflags
from flask import session,abort,request,flash,redirect,url_for
from services.entry_service import add_entry

def __userIsAuthenticated():
        return session.get('logged_in')

def add_new_entry():
    if not __userIsAuthenticated():
        abort(401)
        
    title = request.form['title']
    text = request.form['text']

    add_entry(title,text)
    flash('New entry was successfully posted')
    return redirect(url_for('show_entries'))

Refaktorering (1)/controllers/IndexController.py
from flask import render_template


def index():
    return render_template('index.html')
def no_way():
    return render_template('no_way.html')

Refaktorering (1)/controllers/authenticationController.py
from flask import request, redirect, session, url_for,render_template,flash
from services.authentication_service import add_new_user ,authenticate_user


def create_user():
    error = None
    if request.method == 'POST':
        if request.form['username'] == "":
            error = 'Username needed'
        elif request.form['password'] == "" or request.form['repassword'] == "":
            error = 'Password needed'
        elif request.form['password'] != request.form['repassword']:
            error = 'Password is not the same as the retyped'
        else:
            result = add_new_user(
                request.form['username'],
                request.form['password'])
            if(result['status']=='ok'):
                flash('Successfully created - You can now login')
                return redirect(url_for('authentication.log_in'))
            else:
                error = result['userMessage']
    return render_template(
        'authentication/create.html'
        ,error=error
        )



def log_in():
     error = None
     if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        result = authenticate_user(username,password)
        if(result['status']=='ok'):
            session['logged_in']=True
            session['user_id']=result['user_id']
            flash('You were logged in')
            return  redirect(url_for('profile.user_profile'))
        else:
            error = result['userMessage']
     return render_template(
        'authentication/login.html',
        error=error
        )


def log_out():
    session.pop('logged_in', None)
    flash('You were logged out')
    return redirect(url_for('index.index'))

Refaktorering (1)/controllers/commentController.py
from flask import session,request,redirect,url_for,flash
from services.comment_service import add_comment_to_image

def add_comment():
    if request.method == 'POST':
        # TODO: needs to check for autherization
        image_id = request.form['imageid']
        user_id = session.get('user_id')
        comment = request.form['text']
        add_comment_to_image(image_id,user_id,comment)
        flash('Added comment')

        return redirect(
            url_for(
                'images.get_image', 
                id=image_id)
                )

Refaktorering (1)/controllers/imageController.py
from flask import request, flash, session,redirect,url_for,render_template
from services.image_service import upload, get_image_by_id, share_with_user, unshare_with_user

def get_image(id):
    
    user_id = session.get('user_id')
    result = get_image_by_id(id,user_id)
    if result['status']=='ok':
        return render_template('image/image.html', imageid=id,image=result['image'],usernames=result['usernames'],shares=result['shares'],comments=result['comments'],owner=result['owner'])
    return redirect(url_for('no_way'))

def upload_image():
    if request.method == 'POST':
        file = request.files['file']
        userId = session.get('user_id')
        result = upload(userId,file)

        if(result['status']=='ok'):
            flash('uploaded image: %s' % file.name)
            return redirect(url_for('profile.user_profile'))
        else:
            flash('filetype not allowed')

    return render_template('image/upload.html')

def share_image():
     if request.method == 'POST':
        image_id = request.form['imageid']
        to_userid = request.form['userid']
        user_id = session.get('user_id')
        result = share_with_user(user_id,to_userid,image_id )
        if(result['status']=='ok'):
            flash('Image shared')
            return redirect(url_for('images.get_image', id=image_id))
        

def unshare_image():
    if request.method == 'POST':
        #TODO Autherization check
        shared_id = request.form['shareduser']
        image_id = request.form['imageid']
        unshare_with_user(shared_id)
        flash('Image unshared')
        return redirect(url_for('images.get_image', id=image_id))
    else:
        return redirect(url_for('no_way'))

Refaktorering (1)/controllers/profileController.py
from flask import render_template, session
from services.image_service import  get_images_for_user

def user_profile():
    userId = session.get('user_id')
    result = get_images_for_user(userId)
    return render_template(
        'profile/profile.html',
        images=result['images'],
        shared_images=result['shared_images'])

Refaktorering (1)/routes/authenticationBlueprint.py
from flask import Blueprint
from controllers.authenticationController import create_user,log_in,log_out

autheticationBlueprint = Blueprint('authentication',__name__)

autheticationBlueprint.route('/create', methods=['GET','POST'])(create_user)
autheticationBlueprint.route('/login', methods=['GET','POST'])(log_in)
autheticationBlueprint.route('logout',methods=['GET','POST'])(log_out)

Refaktorering (1)/routes/commentBlueprint.py
from flask import Blueprint
from controllers.commentController import add_comment

commentBlueprint = Blueprint('comments',__name__)

commentBlueprint.route('/add', methods=['POST'])(add_comment)

Refaktorering (1)/routes/imageBlueprint.py
from flask import Blueprint
from controllers.imageController import upload_image,get_image,share_image,unshare_image

imageBlueprint = Blueprint('images',__name__)

imageBlueprint.route('/getimage/<id>', methods=['GET'])(get_image)
imageBlueprint.route('/uploadimage', methods=['GET','POST'])(upload_image)
imageBlueprint.route('/shareimage', methods=['POST'])(share_image)
imageBlueprint.route('/unshareimage', methods=['POST'])(unshare_image)

Refaktorering (1)/routes/indexBlueprint.py
from flask import Blueprint
from controllers.IndexController import index, no_way

indexBlueprint = Blueprint('index',__name__)

indexBlueprint.route('/', methods=['GET'])(index)
indexBlueprint.route('/no_way', methods=['GET'])(no_way)

Refaktorering (1)/routes/profileBlueprint.py
from flask import Blueprint
from controllers.profileController import user_profile

userBlueprint = Blueprint('profile',__name__)

userBlueprint.route('/getprofile', methods=['GET'])(user_profile)

Refaktorering (1)/templates/Profile/profile.html
{% extends "layout.html" %}
{% block body %}
    {% if session.logged_in %}
        <a href="{{ url_for('images.upload_image') }}">Upload image</a>


        <ul class=entries>

            <li><h2>Your images</h2>
                {% for img in images %}
                    <a href="{{ url_for('images.get_image', id=img.get('image_id')) }}">
                        <img src={{ url_for('static', filename = 'img/%s' % (img.get('image'))) }} height=100>
                    </a>
                {% else %}
                    <li><em>Unbelievable. No images so far</em>
                {% endfor %}


            <li><h2>Images shared with you</h2>
                {% for img in shared_images %}
                    <a href="{{ url_for('images.get_image', id=img.get('image_id')) }}">
                        <img src={{ url_for('static', filename = 'img/%s' % (img.get('image'))) }} height=100>
                    </a>
                {% else %}
                    <li><em>Unbelievable. No images so far</em>

                {% endfor %}

        </ul>

    {% endif %}
{% endblock %}

Refaktorering (1)/templates/image/image.html
{% extends "layout.html" %}
{% block body %}
    {% if session.logged_in %}
        <a href="{{ url_for('profile.user_profile') }}">Back</a>

        <ul class=entries>
            <h2>{{ image[0].get('filename') }}</h2>
            <img class="img-center" src={{ url_for('static', filename = 'img/%s' % (image[0].get('image'))) }} height=200>

            {% if owner %}
                <h2>Share Image</h2>

                <form action="{{ url_for('images.share_image') }}" method=post>
                    Share with:
                    <select class="share-select-center" name="userid">
                        {% for u in usernames %}
                            <option value="{{ u.id }}">{{ u.username }}</option>
                        {% endfor %}
                    </select>
                    <input name="imageid" type="hidden" value="{{ imageid }}">
                    <input class="share-input-right" type=submit value=Share>
                </form>

                <form action="{{ url_for('images.unshare_image') }}" method="post">
                    Unshare:
                    <select class="share-select-center" name="shareduser">
                        {% for s in shares %}
                            <option value="{{ s.id }}">{{ s.username }}</option>
                        {% endfor %}
                    </select>
                    <input name="imageid" type="hidden" value="{{ imageid }}">
                    <input class="share-input-right" type="submit" value="Unshare">

                </form>

            {% endif %}

            <li><h2>Comments</h2>
                <form action="{{ url_for('comments.add_comment') }}" method=post class=add-entry>
                    <dl>
                        <input name="imageid" type="hidden" value="{{ imageid }}">
                        <dt>Text:
                        <dd><textarea name=text rows=5 cols=40></textarea>
                        <dd><input type=submit value=Comment>
                    </dl>
                </form>
                {% for msg in comments %}
                    <li><h3>{{ msg.username }}</h3>{{ msg.comment|safe }}
                        {% else %}
                    <li><em>Unbelievable. No comments so far</em>
                {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

Refaktorering (1)/templates/image/upload.html
{% extends "layout.html" %}
{% block body %}
    {% if session.logged_in %}
        <a href="{{ url_for('profile.user_profile') }}">Back</a>
        <ul class=entries>

            <li><h2>Upload image</h2>

                <form action="" method=post enctype=multipart/form-data>
                    <p><input type=file name=file>
                        <input type=submit value=Upload>
                </form>


        </ul>

    {% endif %}

{% endblock %}

Refaktorering (1)/templates/index.html
{% extends "layout.html" %}
{% block body %}
<label class="label-top">
    Welcome to Image-2-Image!!
  </label>
    <br/>
    <label class="label-italic">
    login or create a profile, to start sharing your images!!
    </label>
    <image class="img-center" src="{{ url_for('static', filename = 'img/wizard.jpg') }}" width="400" height="500"/>
{% endblock %}

Refaktorering (1)/templates/layout.html
<!doctype html>
<title>Image-2-Image</title>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
<div class=page>
  <h1>Image-2-Image</h1>
  <div class=metanav>
  {% if not session.logged_in %}
    <a href="{{ url_for('authentication.log_in') }}">log in</a>
    <a href="{{ url_for('authentication.create_user') }}">create</a>
  {% else %}
    <a href="{{ url_for('authentication.log_out') }}">log out</a>
  {% endif %}
  </div>
  {% for message in get_flashed_messages() %}
    <div class=flash>{{ message }}</div>
  {% endfor %}
  {% block body %}{% endblock %}
</div>

Refaktorering (1)/templates/no_way.html
{% extends "layout.html" %}
{% block body %}
    <div>
        <image src="{{ url_for('static', filename = 'img/SayTheMagicWord.gif') }}" width="100%"/>
    </div>
{% endblock %}